### ISSUE TITLE
Can't target a plugin's menu using the generateAssets action when started via CLI

### ISSUE THREAD

**Issue by envex** [adobe-photoshop/generator-core#132]
When running generator-core from the command line to develop a plugin, I'm unable to target the plugin's menu from the generate menu when using the provided sample code.

```
executeAction (app.stringIDToTypeID ("generateAssets"), generatorDesc, DialogModes.NO);
```

However, if I take my plugin and add it to the photoshop plugins/generator folder, it works like a charm.

Is it possible to target menu items that are started from the command-line?

**Comment by umarniz** [comment]
I am having the same problem as the op.

I can see from the generator architecture documentation why this is happening as photoshop creates a new menu section for each KVLR connection but i cant figure out the name of the section that photoshop assigns to my external generator-core.

I really need this functionality in my plugin and need it during development so any help would be greatly appreciated.

**Comment by joelrbrandt** [comment]
@umarniz Unfortunately, what you're looking for simply isn't possible. The "generateAssets" action that can be executed from extendscript only targets the built-in generator (and is intended to only be used for the asset generation feature). Given the intent of the feature, this is unlikely to be fixed.

I'd highly recommend going the route that @envex and @marekhrabe discussed above. In fact, the websocket server infrastructure has now been added directly to generator-core. See `Generator.prototype.startWebsocketServer`:
https://github.com/adobe-photoshop/generator-core/blob/master/lib/generator.js#L1832

For an example of how to use the Websocket server in Generator (both from the plugin side and as a client), see this repo (especially the README):
https://github.com/adobe-photoshop/generator-connection

Let us know if you experience any problems!

cc @iwehrman

**Comment by umarniz** [comment]
@joelrbrandt thank you for such a prompt response. I will work around the problem then.

I'll keep bumping you on issues I come across, cheers!
