### ISSUE TITLE
getDocumentInfo not accurate after resizing canvas

### ISSUE THREAD

**Issue by oddgames-david** [adobe-photoshop/generator-core#206]
Has anyone else experienced issues with the data in getDocumentInfo being incorrect after you resize the canvas then use getDocumentInfo?

I have to move a layer then call getDocumentInfo for it to update correctly.

**Comment by codeorelse** [comment]
Imho this one is fixed (in the 3.2 release).

**Comment by mcilroyc** [comment]
Assigning to myself to verify
