### ISSUE TITLE
scaling with inputRect/outputRect can sometimes cause effects to not be scaled

### ISSUE THREAD

**Issue by joelrbrandt** [adobe-photoshop/generator-core#211]
If there are rounding errors that make inputRect/outputRect not look like an aspect-ratio-preserving transform, then layer effects aren't scaled.

The fix is to detect times where the intended scale is off by 1 pixel from aspect-ratio-preserving, and just change the transform to a square on both the input and output (i.e use something like `inputRect.bottom = inputRect.top + (inputRect.right - inputRect.left)`

We could alternatively / additionally compute the transform as a square in the case that the user originally specified a relative scale in the assets plugin.

Here is a test asset: https://raw.githubusercontent.com/adobe-photoshop/generator-assets-automation/master/test/scaled-layer-effects-2/scaled-layer-effects-2.psd

**Comment by mcilroyc** [comment]
What are the chances this is still an issue...
