### ISSUE TITLE
getPixmap sometimes fails with PS 15.0 due to out of order JS messages

### ISSUE THREAD

**Issue by joelrbrandt** [adobe-photoshop/generator-core#240]
Calling getPixmap results in three messages from PS: one JS message for the JSX evaluation result, another JS message for the bounds, and a pixmap message for the actual pixels.

Poor code reviewing on my part introduced a bug in c7b5063616b. In this commit, if the JSX evaluation message arrived first, the executionDeferred would be rejected. This seems to happen in 15.0 with files containing Smart Objects. In particular, it happens with this file:
http://cl.ly/3w1S3r1P1R3D/download/mask-example.psd

In current Jenkins builds, this file does _not_ exhibit the problem.

**Comment by mcilroyc** [comment]
I guess it is time to close this.  @joelrbrandt please re-open if you think this issue was not fully addressed.  mkay?
