### ISSUE TITLE
npm version need update

### ISSUE THREAD

**Issue by welefen** [adobe-photoshop/generator-core#280]
generator-core in npm version is 3.1.0

but in gihub version is 3.4.0-dev, please update npm version。

**Comment by chrislearn** [comment]
NPM version is too old now.

**Comment by joelrbrandt** [comment]
@mcilroyc Can I coax/trick you into being the person with the keys necessary to update the npm entry for generator-core? If so, please let me know your npm username and I'll add you as an owner.

**Comment by mcilroyc** [comment]
Sure @joelrbrandt  - same username as github.

**Comment by joelrbrandt** [comment]
@mcilroyc You're in!

```
$ npm owner add mcilroyc generator-core
$ npm owner add mcilroyc generator-assets
$ npm owner add mcilroyc generator-cli
```

**Comment by mcilroyc** [comment]
npm updated.  closing this issue.

**Comment by Martin-Pitt** [comment]
Last published three years ago, @mcilroyc want to refresh this?
