### ISSUE TITLE
It is no longer possible to call getPixmap on Smart Objects

### ISSUE THREAD

**Issue by marekhrabe** [adobe-photoshop/generator-core#285]
This functionality (that I was depending on in my Avocode extension) stopped working in 2014.2.2. 

I was calling `getDocumentInfo` (with `expandSmartObjects: true`) on some document that includes smart objects and it correctly returned info about that main document and about all placed ones. Then I used ids of documents from that `placed` property to `getDocumentPixmap` or even `getPixmap` of individual layers of smart objects. There was no need to open them or anything like that - it just worked well in all versions except the latest one. 

There might be a relation to #271 where smart objects code got updated? (just to be clear, this issue is about document ids - that small integer ones, not that long string ones. string ones now work correctly after closing #271)

Can you tell what has changed and if it is desired behavior? For me it seems like a bug because can get whole `documentInfo` about smart objects (including layers), but we are no longer able to use given document and layer ids to retrieve pixmaps of them (so it is kind of useless feature now).

This time I don't believe in presence of some hot fix like in #271, but I'd like to be proven wrong of course :)

**Comment by lucien144** [comment]
+1

**Comment by lucien144** [comment]
:+1:

**Comment by marekhrabe** [comment]
Is there any progress on this issue? Thanks

**Comment by joelrbrandt** [comment]
I filed Watson bug 4036456 in hopes that'll nudge things along

@timothynoel any updates on this?

@marekhrabe thanks for re-pinging us. I'll try to get things moving (or at least get clarity on whether they will move).

**Comment by timothynoel** [comment]
This may be tricky to do in a reliable and performant way, unless we do some smart object work. I'm not sure yet when we'll have time for that.

**Comment by zenopopovici** [comment]
This is such a mess ... makes work so much harder. We use SVGs and exporting every damn thing is AI and saving it from there is really, really frustrating.

**Comment by timothynoel** [comment]
Hoping to add this for the next release. The various ExtendScript Generator methods, including sendLayerThumbnailToNetworkClient that take a document "id" or "documentID" will also accept a "placedID" array of smart object ids (unique strings) within that document. These correspond to ids you get from getDocumentInfo:placed:{} or layer:smartObject:{} in the info/change messages.  This should allow you to mostly work with smartObjects as if they were documents (they normally are just files unless we temporarily load and convert them to documents).   You still won't be able to subscribe to changes to smartObjects or change them (unless they are opened as visible documents in the Photoshop UI).

**Comment by marekhrabe** [comment]
Thanks for great news, Timothy! Fingers crossed it will make it into the next release

**Comment by canoztokmak** [comment]
Hey @timothynoel 
Is this change you mentioned on Oct 21 included in PS version 16.1.2 ? I don't see the documentation updated on generator getPixmap method.
Does ExtendScript supports the placedId array to fetch smart object information?

**Comment by timothynoel** [comment]
Look for 'placedID' on this wiki page: https://github.com/adobe-photoshop/generator-core/wiki/Photoshop-Kevlar-API-Additions-for-Generator API.  Most of the underlying Photoshop ExtendScript APIs that take doc/layer id's (e.g. sendDocumentThumbnailToNetworkClient, sendLayerThumbnailToNetworkClient , sendLayerShapeToNetworkClient, sendDocumentStreamToNetworkClient, sendDocumentInfoToNetworkClient) also support a chain of smart object ids (placeID) that can access layers within smart object 'tree' of a psd. getPixmap in generator's node.js is just a wrapper around the Photoshop ExtendScript API, sendLayerThumbnailToNetworkClient. It should be possible to call that ExtendScript function yourself directly to access smart object info. placedID was a Photoshop 16.1 addition.
