### ISSUE TITLE
Cannot call generator plugins from ExtendScript

### ISSUE THREAD

**Issue by ungsophy** [adobe-photoshop/generator-core#293]
Hi all, 

I follow the instruction in the Wiki pages on [how to call generator plugins from ExtendScript](https://github.com/adobe-photoshop/generator-core/wiki/Calling-Generator-Plugins-from-ExtendScript), but unfortunately I cannot get it to work. The following is my sample code. Am I missing something?

Generator plugin code (main.js):
```javascript
(function () {
    "use strict";

    var MENU_ID    = "my_menu",
        MENU_LABEL = "$$$/JavaScripts/Generator/My Menu/Menu=My Menu";

    var _generator = null,
        _config    = null;

    function generatorHandler(event) {
      var menu = event.generatorMenuChanged;
      if (menu && menu.name !== MENU_ID) return;

      console.log("\nevent: %j", event);
    }

    function initLater() {
      var params = { foo: "bar" };
      _generator.evaluateJSXFile("/path/to/my_extendscript.jsx", params);
    }

   function init(generator, config) {
      _generator = generator;
      _config    = config;

      _generator.addMenuItem(MENU_ID, MENU_LABEL, true, false);
      _generator.onPhotoshopEvent("generatorMenuChanged", generatorHandler);

      process.nextTick(initLater);
    }

    exports.init = init;
    exports._setConfig = function(config) { _config = config; };
}());
```

ExtendScript code (my_extendscript.jsx):
```javascript
alert("message: " + params.foo);   // I see alert message in Photoshop

// This chuck of code doesn't trigger the click on File -> Generate -> My Menu
var generatorDesc = new ActionDescriptor();
generatorDesc.putString(app.stringIDToTypeID("name"), "my_menu");
generatorDesc.putString(app.stringIDToTypeID("sampleAttribute"), "moreInfo");
var returnDesc = executeAction(app.stringIDToTypeID("generateAssets"), generatorDesc, DialogModes.NO);
```

I think the problem might be at ```executeAction(app.stringIDToTypeID("generateAssets"), generatorDesc, DialogModes.NO);```. What does ```app.stringIDToTypeID("generateAssets")``` mean? The Wiki page doesn't say anything on that part.

But if I manually click on File -> Generate -> My Menu, I can see the callback on generator plugin is being called. Any help is appreciated.

Thanks,

**Comment by joelrbrandt** [comment]
Paging @isonno -- Could you please take a look at this?

I seem to remember a limitation that the _only_ Generator menu that could be activated via extendscript was the "Generate Assets" menu for the built-in plugin. But, that seems like an artificial limitation, and lots of folks are requesting this. Is there a way we could help them out?

@ungsophy if you are building a CEP panel, another route to go is to use websockets to communicate between CEP and Generator. Generator-core includes a websocket server for just this purpose. More details are available in #233 (and discussion of this problem is in #132).

**Comment by timothynoel** [comment]
I think the issue Photoshop only sends the menu event to the built-in Photoshop (pipe) connection when it's scripted. When you execute a generate/generateAssets Photoshop just passes the descriptor along in a menuEvent, but only to the built-in connection.  When you actually click the menu, it sends it to the connection (socket or pipe) that added the menu, so we have a bit of a discrepancy there.

**Comment by joelrbrandt** [comment]
@timothynoel Ahh yes, I'd totally forgotten about that limitation. I've added a note about that to the wiki page https://github.com/adobe-photoshop/generator-core/wiki/Calling-Generator-Plugins-from-ExtendScript

@ungsophy I assume you were experiencing this problem when connecting from a Generator process you launched yourself? If so, unfortunately that is "as designed". The web socket route detailed above is the way to go.

If you're experiencing this problem with the built-in Generator process, please let us know (by re-opening this issue and leaving a comment).

Closing as "as designed".
