### ISSUE TITLE
two layer creation doc changed events reported when creating a text layer with ExtendScript

### ISSUE THREAD

**Issue by joelrbrandt** [adobe-photoshop/generator-core#302]
As reported here: https://groups.google.com/forum/#!topic/adobe-generator-dev/sh9ult1AzHI

If you create a text layer in ExtendScript like this:

```
var layer = app.activeDocument.artLayers.add()
layer.kind = LayerKind.TEXT
```

then you get image changed events like this:

```
[531.668] Image 1489 was changed: {
    "version": "1.2.0",
    "timeStamp": 1429262870.488,
    "count": 5,
    "id": 1489,
    "layers": [
        {
            "id": 4,
            "index": 1,
            "bounds": {
                "top": 0,
                "left": 0,
                "bottom": 0,
                "right": 0
            },
            "added": true,
            "type": "layer",
            "name": "Layer 2"
        }
    ],
    "selection": [
        1
    ]
}
[535.724] Image 1489 was changed: {
    "version": "1.2.0",
    "timeStamp": 1429262874.544,
    "count": 6,
    "id": 1489,
    "layers": [
        {
            "id": 5,
            "index": 1,
            "bounds": {
                "top": 0,
                "left": 0,
                "bottom": 0,
                "right": 0
            },
            "added": true,
            "type": "textLayer",
            "name": " "
        }
    ]
}
```

The original reporter says "The issue is that you can't tell layer 4 got changed to layer 5 and no longer exists. It would be better if layer 4 would get a removed-event or just a "metadataonly=true, type=textLayer"-event without creating a new layer."

**Comment by joelrbrandt** [comment]
Assigning to @isonno for investigation, since he's the man who knows about ES. However, @timothynoel might have thoughts, too.

**Comment by joelrbrandt** [comment]
The individual who identified this bug also noted the following:

When you create a text layer and set text in [ExtendScript] and use getDocumentInfo, the bounds-element does not update. I.e. bounds under text-element is non-empty but bounds in the layer-element is all zeros like below. [ExtendScript] code:

```
var layer = app.activeDocument.artLayers.add()
layer.kind = LayerKind.TEXT
layer.content = 'foo'
``

Result of getDocumentInfo for this layer

```
{
  "id":33,
  "index":3,
  "type":"textLayer",
  "name":"properties",
  "bounds":{
    "top":0,
    "left":0,
    "bottom":0,
    "right":0
    },
  "visible":true,
  "clipped":false,
  "generatorSettings":false,
  "text":{
    "textKey":"foo",
    "textClickPoint":{
      "horizontal":{
        "value":10,
        "units":"percentUnit"
        },
      "vertical":{
        "value":10,
        "units":"percentUnit"
        }
      },
    "boundingBox":{
      "left":0.0625,
      "top":-8.937515,
      "right":63.320938,
      "bottom":1.937515
      },
    "bounds":{
      "left":0,
      "top":-10.044067,
      "right":64.211243,
      "bottom":3
      },
    "textShape":[{
      "char":"paint",
      "orientation":"horizontal",
      "transform":{
        "xx":1,
        "xy":0,
        "yx":0,
        "yy":1,
        "tx":0,
        "ty":0
        },
      "rowCount":1,
      "columnCount":1,
      "rowMajorOrder":true,
      "rowGutter":0,
      "columnGutter":0,
      "spacing":0,
      "frameBaselineAlignment":"alignByAscent",
      "firstBaselineMinimum":0,
      "base":{
        "horizontal":0,
        "vertical":0
        }
      }],
    "textStyleRange":[{
      "from":0,
      "to":12,
      "textStyle":{
        "fontName":"Myriad Pro",
        "fontStyleName":"Regular",
        "size":12
        }
      }],
    "paragraphStyleRange":[{
      "from":0,
      "to":12,
      "paragraphStyle":{
        "align":"left"
        }
      }]
    }
  }
```

**Comment by isonno** [comment]
As a work-around, you might try [creating the text layer directly](https://gist.github.com/isonno/af74a58e57502c39472c) using PS events rather than using the DOM (I suspect the duplicate event is due to the DOM, but haven't investigated it yet).

**Comment by joelrbrandt** [comment]
The original reporter of this bug indicates that the problem is still present in CC 2015.

However, as part of Spaces work, @iwehrman noticed that text layer creation stuff has recently changed. So, perhaps something is getting fixed here? Here's the relevant spaces bug: adobe-photoshop/spaces-design#1969

CC @iwehrman

**Comment by joelrbrandt** [comment]
Actually, the original reporter also indicates that the output in CC 2015 has changed slightly when these two lines of ExtendScript are executed:

```
var layer = app.activeDocument.artLayers.add()
layer.kind = LayerKind.TEXT
```

Specifically, he says:

>Behaviour on this has changed a bit on CC2015. Now when I debug through those two lines in ESTK, I get no event on first line and then second line (i.e. when script completes you get event.)

The output is now:

```


[50.024 onImageChange] delta={
  "version":"1.3.0",
  "timeStamp":1437976232.183,
  "count":6,
  "id":1487,
  "layers":[{
    "id":6,
    "index":2,
    "bounds":{
      "top":0,
      "left":0,
      "bottom":0,
      "right":0
      },
    "added":true,
    "type":"textLayer",
    "name":" "
    },{
    "id":5,
    "added":true
    }],
  "selection":[2]
  }
```

He continues:

> So it's still an issue that turning an empty layer to a text layer get's no delta info that the original layer is no more. You have to get full doc info and realize the layer in your data exists no more and you should treat it like it was removed.

**Comment by joelrbrandt** [comment]
User reports this is working correctly in 15.1.1, closing!
