### ISSUE TITLE
out of date pngquant license

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/generator-core#309]
Originally filed by @pornel as adobe-photoshop/generator-assets-automation#22:

-----
I've been informed that Photoshop shipped with a license file for pngquant 1.0, rather than the current version used in Photoshop.

Pngquant has been relicensed since 1.0, and the current version's copyright notices are here:

https://github.com/pornel/pngquant/blob/master/COPYRIGHT

pngquant, libimagequant and and rwpng:

© 1997-2002 by Greg Roelofs; based on an idea by Stefan Schneider.
© 2009-2015 by Kornel Lesiński.

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

pngquant and libimagequant:

© 1989, 1991 by Jef Poskanzer.

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted, provided
that the above copyright notice appear in all copies and that both that
copyright notice and this permission notice appear in supporting
documentation. This software is provided "as is" without express or
implied warranty.

**Comment by joelrbrandt** [comment]
I'll take this one. Thanks @pornel (and @wehrman for re-filing)!

**Comment by joelrbrandt** [comment]
@pornel I'm curious where in the application you saw the out of date PNGQuant license. I can't find it.

The only place the license *should* appear is in this PDF:
http://www.adobe.com/products/eula/third_party/pdfs/adobe_products_eula.pdf
(which is linked from the "Click here for legal notices" link in the About dialog)

Searching that PDF for `pngquant` yields this license:

```
A-1487
Jef Poskanzer, Greg Roelofs, Kornel Lesiński
pngquant.c:
 © 1989, 1991 by Jef Poskanzer.
 Permission to use, copy, modify, and distribute this software and its
 documentation for any purpose and without fee is hereby granted, provided
 that the above copyright notice appear in all copies and that both that
 copyright notice and this permission notice appear in supporting
 documentation. This software is provided "as is" without express or
 implied warranty.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
pngquant.c and rwpng.c/h:

© 1997-2002 by Greg Roelofs; based on an idea by Stefan Schneider.
 © 2009-2014 by Kornel Lesiński.

 All rights reserved.

 Redistribution and use in source and binary forms, with or without modification,
 are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice,
 this list of conditions and the following disclaimer.

 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

The only difference from that and the license at https://github.com/pornel/pngquant/blob/master/COPYRIGHT is the change from `© 2009-2014` to `© 2009-2015`. However, the version we included was from 2014, so what we have appears correct.

If you're finding a license notification somewhere else, I definitely want to get it fixed!

**Comment by pornel** [comment]
The old license is in LegalNotices.pdf in Applications/Adobe Photoshop CC 2015

**Comment by joelrbrandt** [comment]
@pornel Interesting! I wonder how those got out of sync. We'll get it taken care of. Thanks again!

**Comment by joelrbrandt** [comment]
@pornel this is fixed in the next shipping version of PS (and, as you saw, it's already fixed online). Apologies for the hassle! And, thanks for your hard work on pngquant.

**Comment by pornel** [comment]
Thank you
