### ISSUE TITLE
get pixmap of clipped layer

### ISSUE THREAD

**Issue by GDreyV** [adobe-photoshop/generator-core#333]
Hello! Is there any way how I can get "raw" pixmap of layer which has clipping layer? I mean pixmap of layer itself without clipping and other related layers.
E.g. I have following layers:
![Layers](https://cloud.githubusercontent.com/assets/6262948/12776961/f22cfbe6-ca6a-11e5-9ec8-283bcaf465f5.png)
and I want to get pixamp for "Ellipse 2". So I suppose to get image with blue ellipse and transparent background. I run `getPixamap` function with id of required layer. But here's what I got:
![layer-ellipse_2](https://cloud.githubusercontent.com/assets/6262948/12777050/6b3688e0-ca6b-11e5-82cc-6e05113a3080.png)
I got Ellipse 2 plus all layers above, plus clipping layer. I've played a bit with `clipToDocumentBounds` and `includeAncestorMasks` but without any success.
Case to reproduce: [clipped-layers.zip](https://github.com/adobe-photoshop/generator-core/files/115369/clipped-layers.zip)

**Comment by timothynoel** [comment]
I think you need "includeClipBase" to be "includeNone". If you want just the layer without any context, you need ensure that all the include* enums are "includeNone". (along with "clipToDocumentBounds" if you want to include "big data" past the doc bounds).  Here's the relevant bits from the wiki entry for sendLayerThumbnailToNetworkClient:

```
//keys are one of the following values:
//includeAdjustors: adjustors above the layer, default is includeVisible
//includeAncestors: enclosing groups (includes group blending, fx, masks), default is includeAll
//includeChildren: children if layer is a group (includes group blending, fx, masks), default is includeVisible
//includeClipBase: clip base if layer is clipped.  The clip base is a layer that a clipped layer is clipped to, default is includeAll
//includeClipped: clipped layers if layer is clip base, default is includeVisible

//Notes:
//for includeAncestors:
//     includeVisible and includeAll incorporate any blending parameters/masks of the ancestor groups
//     includeVisible returns an empty thumbnail for any layer inside an invisible group
//     includeNone substitutes  default groups for any groups around the layer

desc1.putEnumerated( stringIDToTypeID( "includeAdjustors" ), stringIDToTypeID( "includeLayers" ), includeAdjustors );
desc1.putEnumerated( stringIDToTypeID( "includeAncestors" ), stringIDToTypeID( "includeLayers" ), includeAncestors );
desc1.putEnumerated( stringIDToTypeID( "includeChildren" ), stringIDToTypeID( "includeLayers" ), includeChildren );
desc1.putEnumerated( stringIDToTypeID( "includeClipBase" ), stringIDToTypeID( "includeLayers" ), includeClipBase );
desc1.putEnumerated( stringIDToTypeID( "includeClipped" ), stringIDToTypeID( "includeLayers" ),  includeClipped );

```

**Comment by timothynoel** [comment]
FWIW, there's also ways to make sendLayerThumbnailToNetworkClient ignore the layer's masks, fx, blending etc, too. It's involves sending in "layerSettings" descriptors to apply to the layer(s) before getting the thumbnails to override the layer.  It doesn't sound like that's what you want though.

**Comment by mcilroyc** [comment]
@GDreyV  did that answer your question?

**Comment by GDreyV** [comment]
Sorry, I missed email with the answer. Yeah, "includeClipBase" makes sense. Thanks for help!
