### ISSUE TITLE
Allow plugins to set their own logging level

### ISSUE THREAD

**Issue by rog** [adobe-photoshop/generator-core#337]
It's posible to disable the logger from my plugin without editing this line from the generator-code:
https://github.com/adobe-photoshop/generator-core/blob/master/lib/generator.js#L28

**Comment by mcilroyc** [comment]
This is not currently supported, but is a reasonable request.  I'd be interested to know how this is impacting you though.  I'm going to change the name of the issue to reflect the request, let me know if you disagree @rogr.

**Comment by rogr** [comment]
Thank you @mcilroyc, and yeah, I think this is a better name for this issue.

This is my case problem:

I'm using [node-progress]( https://github.com/tj/node-progress) to show a progress bar of the assets I'm generating, but the logger from the `generator-core` makes that the progress bar doesn't show in one line.

I will see if I can do a PR.
