### ISSUE TITLE
Text length for last paragraph

### ISSUE THREAD

**Issue by shalanah** [adobe-photoshop/generator-core#353]
Looks like the last paragraph is one character longer than the string provided. Just wondering if this is a bug, or intentional. Are we just missing the last character of the paragraph?

``` javascript
{
  "textKey": "testing",
  "textStyleRange": [
    {
      "from": 0,
      "to": 8, // should be 7 unless an assumed end of paragraph character
      "textStyle": {}
    }
  ],
  "paragraphStyleRange": [
    {
      "from": 0,
      "to": 8, // should be 7 unless an assumed end of paragraph character
      "paragraphStyle": {}
    }
  ]
}
```

**Comment by mcilroyc** [comment]
@shalanah could you please provide a little more context?  What are the simple steps to reproduce the data you included in the bug description?

**Comment by shalanah** [comment]
Sure, no problem!

#### Example 1:
- Create a textbox with the text "Lorem\rIpsum"

##### Paragraph 1: "Lorem\r"
Looking at the first `paragraphStyleRange` we have `from: 0` and `to: 6` which works perfectly. It also gives us an accurate length of 6 characters ( 6 - 0 ).

##### Paragraph 2: "Ipsum"
Here we have `from: 6` and end with `to: 12`. This gives us an inaccurate length of 6 characters ( 12 - 6 ) when "Ipsum" is only 5 characters long.
```javascript
"text": {
    "textKey": "Lorem\rIpsum",
    "paragraphStyleRange": [
        {
            "from": 0, // good
            "to": 6, // good
            "paragraphStyle": '...'
        },
        {
            "from": 6, // good
            "to": 12, // one character too long
            "paragraphStyle": '...'
        }
    ]
}
```

#### Example 2:
- Create a text box with just the text "Lorem"

##### Paragraph 1: "Lorem"
Looking at the `paragraphStyleRange` we have `from: 0` and `to: 6`. This gives us the inaccurate length of 6 characters when "Lorem" is only 5 characters long.

```javascript
"text": {
    "textKey": "Lorem",
    "paragraphStyleRange": [
        {
            "from": 0, // good
            "to": 6, // one character too long
            "paragraphStyle": '...'
        }
    ]
}
```

**Comment by mcilroyc** [comment]
I was able to reproduce this, and I can't see how this would be considered correct.  But I also can't make a strong case for trying to change it.

Another way to look at it... If you don't factor `\r` in the paragraph text then they're both off by one!
lorem = 5
ipsum = 5

cc: @timothynoel in case you feel that this could/should be addressed in photoshop proper.
