### ISSUE TITLE
Listen to changes from tools panel

### ISSUE THREAD

**Issue by izayarniy** [adobe-photoshop/generator-core#355]
Hello. 
I want to listen tools' panel changes (parameters of selected tool e.t.c)
For example if user changes brush size  or opacity I want to know it.
Is there any way to listen or create such events ?

toolChanged event didn't help. It occurs only when another tool is selected.
I didn't find any helpful information about how to do this in photoshop sdk connection.

**Comment by mcilroyc** [comment]
Sorry, not currently possible through the generator interface.
