### ISSUE TITLE
getPixmap not working with shapeLayer

### ISSUE THREAD

**Issue by mitya777** [adobe-photoshop/generator-core#357]
After the upgrade to 2015.5 I'm not able to get generator.getPixmap() to work with this shapeLayer.

<img width="273" alt="screen shot 2016-06-23 at 12 52 49 am" src="https://cloud.githubusercontent.com/assets/721277/16292182/0145f020-38dd-11e6-9165-cb3a101aa8b4.png">

Here is the error message when using the generator-assets with the built in generator:

```
[debug:generator-assets 00:47:05.757 assetmanager.js:560:22] handleChange: { layers: { '70': { layer: [Object], index: 242, changes: [Object] } },
  id: 195,
  timeStamp: 1466657225.754,
  count: 7 }
[info:generator-assets 00:47:06.070 rendermanager.js:157:30] RenderManager active
[info:generator-assets 00:47:06.071 rendermanager.js:178:26] Rendering: Button BG.png (0;1)
[error:generator-assets 00:47:06.267 assetmanager.js:449:34] Render failed: Button BG.png { [Error: Got a pixmap with zero bounds.] zeroBoundsError: true }
[info:generator-assets 00:47:06.267 rendermanager.js:190:38] RenderManager idle
```

Update: textLayers don't seem to work either, although it does work for a layerSelection.

**Comment by chadrolfs** [comment]
Yes, unfortunately we shipped with this bug and are aware of it.  We have a fix ready to be released that will hopefully go out VERY soon!  
https://helpx.adobe.com/photoshop/kb/generate-and-export-as-failure.html

**Comment by chadrolfs** [comment]
https://jira.corp.adobe.com/browse/PS-3397

**Comment by mitya777** [comment]
Is there a rough time line for this?

**Comment by chadrolfs** [comment]
Yes, but nothing I can share publicly unfortunately.  Very soon...
