### ISSUE TITLE
README link broken

### ISSUE THREAD

**Issue by Jolg42** [adobe-photoshop/generator-core#367]
Hi,

Is it possible to fix the link in the [README](https://github.com/adobe-photoshop/generator-core/blob/master/README.md):
`Script your first Adobe Generator plugin for Photoshop -> http://tomkrcha.com/?p=3896` 

![screenshot 2016-10-10 at 11 44 35](https://cloud.githubusercontent.com/assets/1328733/19232239/f59cb08a-8ede-11e6-8bb5-9a3753fe6950.jpg)

**Comment by zklinger2000** [comment]
Yes, I'd like to see this tutorial as well!

**Comment by iwehrman** [comment]
That blog post may have been lost to the sands of time, but a fork of the sample plugin it referenced is here: https://github.com/adobe-photoshop/generator-getting-started

**Comment by zklinger2000** [comment]
My problem is I can't even figure out how to get it show up in the Menu, even though it says it is working.  And the generator-assets example is confusing me with its dummy-menu explanation.

**Comment by mcilroyc** [comment]
Removed stale link.  RIP tomkrcha blog.
