### ISSUE TITLE
Is there a possibility to export a PNG with zero metadata?

### ISSUE THREAD

**Issue by talecrafter** [adobe-photoshop/generator-core#372]
Hello. Don't know if this is the right place to ask. If not, sorry.

The problem I am facing is this: Using Photoshop->File->Generate->ImageAssets in an automated pipeline where I want to check if generated files got changed for real with an MD5 checksum. When I just toggle a layer off and on again and save, it get's a different MD5, probably because of a modification date in the XMP Metadata.
Another test I made: A single image, using the Export for Web, PNG, and MetaData set to none also yields to different checksums when adding and removing a pixel. Which makes me fear that this metadata gets added in an application layer that's not accessible from the outside.

Is there an option in the config to suppress this, to get an image with zero or non-changing meta data?

**Comment by mcilroyc** [comment]
I just did a very simple, quick test of this and I believe that PNGs created with FLITE transcoder (not imagemagick) do not contain the mod time metadata.  I was able to produce identical files.  FLITE will soon be the default, but you can configure the `use-flite` option via config file.  https://github.com/adobe-photoshop/generator-assets/wiki/Configuration-Options.

Please re-open this bug if you find this workaround insufficient, or have other counter examples even with FLITE.

**Comment by talecrafter** [comment]
That's awesome to hear. Thank you very much.
