### ISSUE TITLE
Automate assets generation thought command line

### ISSUE THREAD

**Issue by Milewski** [adobe-photoshop/generator-core#374]
Hello, i am looking for a way to give a psd in and get all the assets generated out, is it possible with this current project? or the limitation lies on the photoshop itself? 

i have tried using the generator-cli which just throws me errors.. 

in short i have a psd with all the "assets naming set", and what i am trying to do is: 

```generator --in some/psd/file.psd --out assets-folder/ ```

I want to automate the process, by integrating this assets generation directly on the my CI, however i don't seen to get this working. i need a photoshop server? how am i supposed to get one?

**Comment by mcilroyc** [comment]
@Milewski I think these questions are better suited for our group forum here: https://groups.google.com/forum/#!forum/adobe-generator-dev

I'll close this issue unless we can identify a specific bug that needs to be resolved.

A few answers...
- What you are trying to do would probably require building a plug-in that is *based on* the [Generator Assets](https://github.com/adobe-photoshop/generator-assets) plugin which handles layer-naming parsing and orchestrates the creation of all the assets
- To build such a command line app I think you'd need to either 
  - create a generator plugin that exposed a websocket interface you could connect to
  - use the "remote" generator process described [here](https://github.com/adobe-photoshop/generator-core/wiki/Generator-Development-Environment-Setup)
- Photoshop needs to be run locally and have access to the PSD on the filesystem

**Comment by Milewski** [comment]
Oh just for the record, if someone come here from google loooking for what i just proposed.. i have eventually build this thanks to @mcilroyc for showing the direction.

you can find it here [https://github.com/Milewski/generator-exporter](https://github.com/Milewski/generator-exporter)
