### ISSUE TITLE
streamPixmap() argument mismatch

### ISSUE THREAD

**Issue by pixels4nickels** [adobe-photoshop/generator-core#380]
The signature of streamPixmap in convert.js is:
**function streamPixmap(binaryPaths, pixmap, outputStream, settings, logger)** 
Yet is never called with the last argument "logger" from savePixmap, which causes exceptions due to logger.log being undefined.

I have monkey patched this in my own extension, removing the argument and logger usage. But this should seriously be fixed. Not sure how this made it into the CC2017 release to be honest.

**Comment by zimag** [comment]
Same here. I had to comment out the logger lines. Maybe if it could be a global object, not an argument passed around, we could redefine it.

**Comment by pixels4nickels** [comment]
I could not figure out how to fix this for release. @zimag were you able to get this working in CC2017?

**Comment by mcilroyc** [comment]
See #393.  I agree this was a gross omission.  I also agree that there is certainly a better approach than passing this logger object around, but I hope that above fix will be sufficient for now.

**Comment by mcilroyc** [comment]
fix included in Photoshop 2018
