### ISSUE TITLE
Photoshop communication error

### ISSUE THREAD

**Issue by andrejoblakceltra** [adobe-photoshop/generator-core#384]
When setting up generator development environment exactly as described here: 
https://github.com/adobe-photoshop/generator-core/wiki/Generator-Development-Environment-Setup 
and then running generator with `node app.js -v -f ../plugins` results in the following error:
```
[info:core 14:46:02.233 C:\development\photoshop\generator\generator-core\lib\generator.js:103:17] Launching with config:
{}
Communication error: 2
[warning:core 14:46:02.255 C:\development\photoshop\generator\generator-core\lib\generator.js:131:25] photoshop communications error: {"error":"Photoshop communication error: 2"}
Communication error: 2
[warning:core 14:46:02.258 C:\development\photoshop\generator\generator-core\lib\generator.js:131:25] photoshop communications error: {"error":"Photoshop communication error: 2"}
[info:core 14:46:02.261 C:\development\photoshop\generator\generator-core\lib\generator.js:117:25] Photoshop connection closed
Exiting with code 0: Generator close event
```
I'm using:
* node version 5.4.0
* npm version 5.0.2
* generator core version 3.11.0 (commit 41ed188450bbd1d7a65808067963e0aaa9d6ba2b)
* generator assets version 2.9.0 (commit e15e68ba81751f9b585152eb9b5e1f2ec2113e6f)
* Photoshop CC 2017.1.1 (20170425.r.252 x64)
* Windows 10 Professional

I get the same error on MacOS with:
* node version 6.10.3
* npm version 3.10.10
* generator core version 3.11.0 (commit 41ed188450bbd1d7a65808067963e0aaa9d6ba2b)
* generator assets version 2.9.0 (commit e15e68ba81751f9b585152eb9b5e1f2ec2113e6f)
* Photoshop CC 2017.0.1 (20161130.r.29 x64)
* Mac OS X version 10.11.3

This started happening today when I updated generator core from the repository.

**Comment by mcilroyc** [comment]
The master branch of this repository is not guaranteed to run on the *released* version of photoshop.  Please use the version of generator-core that's equivalent to the built-in version of generator included in your photoshop (likely 3.8.4).
