### ISSUE TITLE
generator doesn't work in Photoshop 2018 on mac

### ISSUE THREAD

**Issue by GDreyV** [adobe-photoshop/generator-core#400]
I just want to duplicate adobe topic to be sure it's investigate from both sides - Photoshop and generator core. In some environments savepixmap couses following error: Error with convert's STDIN: Error: write EPIPE. So it's impossible to save any bitmaps.
Here's discussion thread on Adobe support forum: https://forums.adobe.com/message/9941050.

**Comment by mcilroyc** [comment]
Thanks @GDreyV , I'm aware of that support forum thread.  So far no one here can repro the issue.  I know you're an expert, so any help is appreciated.

**Comment by mcilroyc** [comment]
@GDreyV any chance you could try out the alternate `convert` binary recently posted [here](https://forums.adobe.com/message/10080308#10080308) (if you have a system on which it currently fails)?

**Comment by GDreyV** [comment]
Sorry, that I forgot to post feedback here. Yes, this workaround works well for all customers who use such systems. I hope it will be included in the next Photoshop release :)

**Comment by mcilroyc** [comment]
@GDreyV just to be clear, a new binary version was posted to that forum that is a *candidate* for future release.  The workaround you are talking about may be to use the *old* version of `convert` from the previous version of photoshop.  I'm interested in the viability of the new binary.

**Comment by ghenania** [comment]
Hey @mcilroyc 
Just tested the version of convert posted on the forum and it has fixed the problem for me!
