### ISSUE TITLE
How can I use savePixmap to save layer's data with stream format

### ISSUE THREAD

**Issue by walkingxian** [adobe-photoshop/generator-core#410]
I  want to use savePixmap to get a node stream but not a file. Thanks for answer!

**Comment by mcilroyc** [comment]
It may be helpful to look at `Generator.prototype.streamPixmap`
https://github.com/adobe-photoshop/generator-core/blob/master/lib/generator.js#L1707

Also look/post here:
https://groups.google.com/forum/#!forum/adobe-generator-dev

Closing this issue since it is not a "bug".
