### ISSUE TITLE
Too many commands in queue, dropping message

### ISSUE THREAD

**Issue by RealBuddy** [adobe-photoshop/generator-core#417]
Hi Cory,
I'm getting this error:
[warning:core 23:02:04.464 generator.js:133:30] Photoshop error { id: 4079,
  body: 'Too many commands in queue, dropping message' }

I guess it comes from this line:
https://github.com/adobe-photoshop/generator-core/blob/24a2c4e38aef79adb42869f200778ab52de4ef36/lib/generator.js#L133

Could you give me a clue why it may happen? and How to avoid that?
Thank you!

**Comment by mcilroyc** [comment]
@RealBuddy The underlying connection to Photoshop has a command queue limit (I think 50).  If you are writing your own plugin, you should try to throttle the number of commands (especially long-running commands) you send to Photoshop at the same time.  I'm aware of one way to encounter this using the generator-assets plugin: trying to export an SVG with a large number of pixel layers.

**Comment by RealBuddy** [comment]
Thank you for such a quick answer!
