### ISSUE TITLE
Bump Node.js version

### ISSUE THREAD

**Issue by zhitomir-oreshenski-mm** [adobe-photoshop/generator-core#433]
Hi,

As per [official docs](https://github.com/adobe-photoshop/generator-core/wiki/Generator-Development-Environment-Setup) it seems that Photoshop currently supports very old Node.js **v4.8.4** version (Security support ended in 2018) and evaluating **v8.11.1**. Is there any time line for this action?

Best regards,
Zhi

**Comment by mcilroyc** [comment]
I updated the wiki page you referenced, thanks
