### ISSUE TITLE
Automated testing of generator

### ISSUE THREAD

**Issue by joelrbrandt** [adobe-photoshop/generator-core#80]
Right now, the solution for automated testing of Generator inside Photoshop is very hackish. This is because the automated test framework uses ExtendScript and so does Generator -- two different entities can't use ExtendScript at the same time.

Going forward, the right solution will probably look something like:
1. Build a plugin for Generator that can drive automated testing
2. Figure out how to hook reporting of automated test results in to the Photoshop automated test framework
3. Figure out how the automated test framework for Photoshop can launch Generator's automated tests.

The automated tests should cover (at least) the following:
1. Performance tests -- does data come across the pipe at the rate we expect
2. Protocol/data tests -- when we ask for information from a series of complicated PSDs, do we get the information back that we expect

**Comment by mcilroyc** [comment]
works like a charm.  Exposing g-a-a to automated test frameworks is.. logged elsewhere.
